# baseURL = "https://krishna-chandran.github.io/resume/"

baseURL = "http://localhost:1313/resume"
languageCode = "en-us"
title = "Krishnakumar Chandran"
theme = 'hugo-theme-flat'


enableRobotsTXT = true
hasCJKLanguage = true
paginate = 8

# these values are hugo built in markup config
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
tabWidth = 4


[taxonomies]
category = 'categories'
tag = 'tags'

[params]
description = "Example site for hugo-theme-flat"
mainSections = ['experience','education','projects']




# you can set multi row of footers like these
[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Creative Commons Attribution 4.0 International"
url = "https://creativecommons.org/licenses/by/4.0/"
pre = "Copyright <a href=\"https://creativecommons.org/licenses/by/4.0/\">CC BY-4.0</a>"

[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Hugo"
url = "https://gohugo.io"
pre = "Powered by <a href=\"https://gohugo.io\">Hugo</a>"
[[params.footer_rows.items]]
name = "theme flat"
url = "https://cgit.leafee98.com/hugo-theme-flat.git"
pre = "Theme <a href=\"https://git.leafee98.com/leafee98/hugo-theme-flat.git\">hugo-theme-flat</a>"


[[menus.main]]
name = "Experience"
url = "/experience/"
weight = 30

[[menus.main]]
name = "Education"
url = "/education/"
weight = 40

[[menus.main]]
name = "Projects"
url = "/projects/"
weight = 40

[[menus.main]]
name = "Blog"
url = "/blog/"
weight = 40

[[menus.main]]
url = "/about/"
name = "About Me"
weight = 80